### ISSUE TITLE
Visibility.is_visible is always overwritten after mesh building

### ISSUE THREAD

**Issue by rparrett** [Nilirad/bevy_prototype_lyon#108]
So it's seemingly impossible to spawn a shape in an initially invisible state.

I toyed with removing this behavior by setting `is_visible` to true in `impl Default for ShapeBundle` and removing the `visible.is_visible = true` in `complete_shape_bundle`. This didn't seem to harm anything, but it seems like this must be happening for a reason.

In my own code, I've worked around this with
```rs
struct ShapeStartsInvisible;

// ...

app.add_stage_after(
        bevy_prototype_lyon::plugin::Stage::Shape,
        "after_shape",
        SystemStage::parallel(),
    );
app.add_system_to_stage("after_shape", shape_visibility_fix.system());

// ...

fn shape_visibility_fix(
    mut invis: Query<&mut Visible, (Changed<Handle<Mesh>>, With<ShapeStartsInvisible>)>,
) {
    for mut visible in invis.iter_mut() {
        visible.is_visible = false;
    }
}
```

But adding a similar component to `bevy_prototype_lyon` to control initial visibility seems like an option if it turns out that having a visible shape without a mesh hanging around for a bit is harmful.

If you'd like to point me in one direction or the other I'd be happy to send a PR over.

**Comment by Nilirad** [comment]
Thanks for pointing it out. I understand what the issue is. As soon as possible, I will put visibility to default in `ShapeBundle::default` and remove setting visibility to true in complete_shape_bundle.

I did that because I've put a dummy quad mesh during `ShapeBundle` creation, but it is unnecessary to set it to invisible, since it is immediately replaced by the shape even before the frame gets rendered.
