### ISSUE TITLE
Path not exposed from this module?

### ISSUE THREAD

**Issue by cpetzold** [Nilirad/bevy_prototype_lyon#119]
I'm trying to query for a Path component but it looks like Path isn't exported. Should I be using `lyon_tesselation` as a peer dependency and importing `lyon_tessellation::path::Path`? I'm trying to follow your example which queries for `Path` here: https://github.com/Nilirad/bevy_prototype_lyon/blob/master/examples/change_shape_example.rs#L43

**Comment by cpetzold** [comment]
Oh I see, `Path` was recently added to `entity::Path`, but isn't yet published yet. Is this crate safe to use from master?

**Comment by Nilirad** [comment]
Yeah, I had to make a `Path` newtype to `#[derive(Component)]` on it (see #118).

I plan to release the next version when Bevy 0.6 gets published. In the meantime if you depend on Bevy `main` it makes sense to use the `master` branch. Otherwise, if you're on Bevy 0.5 you can use `bevy_prototype_lyon v0.3.1` which is a bit outdated btw.

**Comment by JasonKraft** [comment]
I'm not sure this is completely resolved:
> Otherwise, if you're on Bevy 0.5 you can use `bevy_prototype_lyon v0.3.1`

Based on my testing the example @cpetzold references does not work with Bevy 0.5 and bevy_prototype_lyon 0.3.1. Is there a proper way to update the shape for those versions?
