### ISSUE TITLE
Mesh2dHandle points to no asset

### ISSUE THREAD

**Issue by repelmoine** [Nilirad/bevy_prototype_lyon#245]
Hello,
In my project, I wanted to be able to pick shapes from **bevy_prototype_lyon** using [bevy_mod_picking](https://github.com/aevyrie/bevy_mod_picking).

I'm new in bevy but I tried debugging and found that in version 0.10 the entity had an Aabb component and that the Mesh2dHandle component was associated with an asset.
![capture_version_0 10](https://github.com/Nilirad/bevy_prototype_lyon/assets/23308855/1a1d7c8a-90d2-4d82-9fc8-8a1e89d35156)

Since version 0.11, there is no longer an Aabb component and Mesh2dHandle points to no asset.
![capture_version_0 11](https://github.com/Nilirad/bevy_prototype_lyon/assets/23308855/740feb92-2e8e-4ed6-afe6-0727ff782df2)

I've noticed that if i modify the following line, the code works again. I don't understand what are the impacts this change might have, but it solves my problem and the shapes are pickable as the Mesh2dHandle is linked to an asset again.

https://github.com/Nilirad/bevy_prototype_lyon/blob/0351fbddca346453f78d401497728a21ea49a9ee/src/plugin.rs#L132
to 
```suggestion
RenderAssetUsages::all()
```

Thanks for all :heart:

**Comment by ramneekhanda** [comment]
any hope for a fix?

**Comment by telans** [comment]
It seems like the missing Aabb component issue is back with the in progress bevy 0.16 version.

I'm inserting a `Shape` when spawning my entity and updating the path later during runtime, the mesh is losing it's `mesh_picking` interaction. Likely because of https://github.com/bevyengine/bevy/issues/18221.
Manually calling `recompute_aabb()` on the mesh after updating the path restored picking.
