### ISSUE TITLE
Removing the ShapeBundle generates warnings

### ISSUE THREAD

**Issue by jomala** [Nilirad/bevy_prototype_lyon#69]
I need to regularly replace a single shape with another, which I am achieving with `Commands::<ShapeBundle>::remove(shape_entity)`. However, this often but not always triggers the following warning log: `WARN bevy_ecs::system::commands: Failed to remove components "bevy_prototype_lyon::entity::ShapeBundle" with error: missing lyon_path::path::Path component. Falling back to inefficient one-by-one component removing.`.

Related to https://github.com/Nilirad/bevy_prototype_lyon/issues/11 perhaps?

**Comment by Nilirad** [comment]
That's strange, `bevy_prototype_lyon` doesn't add/remove components to `ShapeBundle`s.

I did a similar thing with shape replacement in the demo example (the polygon in particular, look at the `replace_polygon` system), but I replaced the entire entity instead of the bundle.

**Comment by jmlMetaswitch** [comment]
Okay, thank you! I'll test that later but I assume it will work for me too. I was trying to use `remove()` rather than `despawn()` and perhaps the former hits issues with ordering during the removal that the latter doesn't. 

Might be worth documenting that the bundle spawns a single entity that can be tagged (or the Entity handle stored using `current_entity()` presumably) and then removed using `despawn()` later.

**Comment by jomala** [comment]
Okay, thank you! That works. I was trying to use remove() rather than despawn() and perhaps the former hits issues with ordering during the removal that the latter doesn't.

Might be worth documenting that the bundle spawns a single entity that can be tagged (or the Entity handle stored using `current_entity()`) and then removed using despawn() later.

**Comment by Nilirad** [comment]
Closing this since the new API allows changing shapes without respawing the entity.
